function(enable_doxygen use_doxygen)
  if(use_doxygen)
    set(DOXYGEN_CALLER_GRAPH YES)
    set(DOXYGEN_CALL_GRAPH YES)
    set(DOXYGEN_EXTRACT_ALL YES)
    find_package(Doxygen REQUIRED dot)
    doxygen_add_docs(doxygen-lib-docs ${PROJECT_PER_DIR} ALL)

  endif()
endfunction()
