name: CI

on: [ push, pull_request ]

jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        run: |
          TASKS=$(echo $(cat .github/workflows/build-matrix.json) | sed 's/ //g' )
          echo "::set-output name=matrix::$TASKS"

  build-and-test:
    needs: matrix
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: ${{ fromJson(needs.matrix.outputs.matrix) }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'



      - name: Install conan
        shell: bash
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install conan

      - name: Install Doxygen
        if: ${{ runner.os }} == "Linux" || ${{ runner.os }} == "macOS"
        shell: bash
        run: |
          if [[ ${{ runner.os }} == 'Linux' ]]; then
            sudo apt-get clean && sudo apt-get update && sudo apt-get install -y doxygen graphviz
          elif [[ ${{ runner.os }} == 'macOS' ]]; then
            brew install doxygen graphviz
          elif [[ ${{ runner.os }} == 'Windows' ]]; then
            echo "Deferring to chocolatey"
          fi

      - name: Chocolatey install Doxygen
        if: ${{ runner.os }} == "Windows"
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install doxygen.install graphviz --no-progress

      - name: Source profile
        if: runner.os == 'Linux'
        shell: bash
        run: source ~/.profile

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.9
        with:
          cmake-version: '3.21'

      - name: Use cmake
        run: cmake --version

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        env:
          CC: ${{ matrix.config.cc }}
          CXX: ${{ matrix.config.cxx }}
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DWARNINGS_AS_ERRORS=TRUE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --build . --target all tests

      - name: Run Tests
        working-directory: ${{runner.workspace}}/build
        run: |
          GTEST_OUTPUT=xml:gtest-report-${{ matrix.config.name }}.xml ctest . --verbose

      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: gtest-results
          path: ${{ runner.workspace }}/build/**/gtest-report-${{ matrix.config.name }}.xml

  publish-gtest-results:
    name: "Publish GTest Results"
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          name: gtest-results
          path: ${{ runner.workspace }}/artifacts/gtest-results_downloaded

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ${{ runner.workspace }}/artifacts/gtest-results_downloaded/**/*.xml

  installation-test:
    name: CMake ${{ matrix.config.name }} Install
    runs-on: ${{ matrix.config.os }}
    needs: build-and-test
    strategy:
      matrix:
        config: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - name: Install
        working-directory: ${{runner.workspace}}/build
        run: |
          cmake --install . --prefix=$GITHUB_WORKSPACE/installation

      - name: List Install Directory
        working-directory: ${{runner.workspace}}/installation
        run: |
          ls



